site_name: R-Epi-Analytics-Documentations
site_url: https://phacdatahub.github.io/R-Epi-analytics-template/


theme:
  name: material
  palette:
    primary: indigo
    accent: blue

repo_url: https://phacdatahub.github.io/R-Epi-analytics-template/

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://phacdatahub.github.io/R-Epi-analytics-template

plugins:
  - search:
      separator: '[\s\-\.]+'
  - mkdocstrings:
      handlers:
        python:
          paths: [api/src]

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences      


nav:
  - Home: index.md
  - Documentation : 
    - How To :
      - How to Use: documentation/how_to/How-to-adopt-template.md
      - How to Adopt Template: documentation/how_to/How-to-adopt-template.md
      - How to Run Trivy Locally: documentation/how_to/How-to-run-trivy-locally.md
      - How the website is built : documentation/how_to/How-website-works.md
      - How to Update Pages: documentation/how_to/How-to-update-pages.md
    - Tech Stack: 
      - Docker: documentation/documentation/techstack/Docker.md
      - Mkdocs: documentation/techstack/Mkdocs.md
      - Trivy : documentation/techstack/trivy.md
      - R : documentation/techstack/R.md
      - Trivy Ignored Files: Trivy_ignored_files.md
