theme:
  name: material
  font:
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"  
      scheme: default
      primary: blue grey
      accent: light blue    
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light blue 
      toggle:
        icon: material/brightness-2
        name: Switch to light mode


site_name: R-Epi-Analytics-Documentations
site_url: https://phacdatahub.github.io/R-Epi-analytics-template/
repo_url: https://phacdatahub.github.io/R-Epi-analytics-template/

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://phacdatahub.github.io/R-Epi-analytics-template

plugins:
  - search:
      separator: '[\s\-\.]+'
  - mkdocstrings:
      handlers:
        python:
          paths: [api/src]

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences

nav:
  - Home: index.md
  - Documentation : 
    - How To :
      - How to Use: how_to/How-to-adopt-template.md
      - How to Adopt Template: how_to/How-to-adopt-template.md
      - How to Run Trivy Locally: how_to/How-to-run-trivy-locally.md
      - How the website is built : how_to/How-website-works.md
      - How to Update Pages: how_to/How-to-update-pages.md
    - Tech Stack: 
      - Docker: techstack/Docker.md
      - Mkdocs: techstack/Mkdocs.md
      - Trivy : techstack/trivy.md
      - R : techstack/R.md
      - Trivy Ignored Files: Trivy_ignored_files.md
