steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: build-if-tag-created
    entrypoint: 'bash'
    dir: rstudio
    args:
      - '-c'
      - |
        if [[ -n "$TAG_NAME" ]]
        then
          echo "northamerica-northeast1-docker.pkg.dev/${PROJECT_ID}/analytics-template/r-studio:$TAG_NAME" > /workspace/imagename
          image=$(cat /workspace/imagename)
          docker build -t $image .
        else
          exit 0
        fi

  - name: 'gcr.io/cloud-builders/docker'
    id: push-if-tag-created
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ -n "$TAG_NAME" ]]
        then
          image=$(cat /workspace/imagename)
          docker push $image
        else
          exit 0
        fi
