name: R Shiny CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.3.3'  # Set your desired R version here
      
    - name: Install dependencies
      run: |
        R -e 'source("src/applications/install.R")'
      
    - name: Check if Shiny app runs
      run: |
        R -e 'shiny::runApp("src/applications/app.R", port = 3838, host = "0.0.0.0") &'
        sleep 5
        curl -I http://localhost:3838  # Check if the app responds with headers
        killall R  # Stop the Shiny app
      
    - name: Check R code style
      run: |
        R -e 'lintr::lint_package()'
