name: R Shiny CI

on:
  push:
    branches:
      - main
    # paths:
    #   - "rstudio-image/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - name: Hadolint Action
      #   uses: hadolint/hadolint-action@v3.1.0
      #   with:
      #     dockerfile: ./rstudio-image/Dockerfile

      - name: "Set image name"
        run: |
          echo "IMAGE_NAME=rstudio-env" >> $GITHUB_ENV

      - name: Build an image from Dockerfile
        working-directory: app
        run: |
          docker build -t $IMAGE_NAME .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
